
license = "All rights reserved" 
loaderVersion = "[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
modLoader = "javafml" #mandatory

[[mods]] #mandatory
authors = "Love, Cheese and small house plants" #optional
credits = "Thanks for this example mod goes to Java" #optional
description = '''
This is a long form description of the mod. You can write whatever you want here
Have some lorem ipsum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mollis lacinia magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sagittis luctus odio eu tempus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque volutpat ligula eget lacus auctor sagittis. In hac habitasse platea dictumst. Nunc gravida elit vitae sem vehicula efficitur. Donec mattis ipsum et arcu lobortis, eleifend sagittis sem rutrum. Cras pharetra quam eget posuere fermentum. Sed id tincidunt justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
''' 
displayName = "Example Mod" #mandatory
logoFile = "examplemod.png" #optional
modId = "rts" #mandatory
version = "${file.jarVersion}" #mandatory

[[dependencies.examplemod]] #optional
mandatory = true #mandatory
modId = "forge" #mandatory
ordering = "NONE" 
side = "BOTH" 
versionRange = "[41,)" #mandatory

[[dependencies.examplemod]]
mandatory = true
modId = "minecraft"
ordering = "NONE"
side = "BOTH"
versionRange = "[1.19,1.20)"
